
#Rock settings
[Rocks]
	rock = true
	granite_rock = false
	diorite_rock = false
	andesite_rock = false
	sand_rock = false
	red_sand_rock = false
	gravel_rock = false
	end_stone_rock = false
	netherrack_rock = false
	soul_soil_rock = false

#Stick settings
[Sticks]
	oak_stick = true
	spruce_stick = true
	birch_stick = true
	acacia_stick = true
	jungle_stick = true
	dark_oak_stick = true
	crimson_stick = false
	warped_stick = false

#Misc settings
[Misc]
	pinecone = false
	geyser = false
	nether_geyser = false
	seashell = false
	starfish = false
	underwater_seashell = false
	underwater_starfish = false

